### ISSUE TITLE
Support display of disconnected triangulations

### ISSUE THREAD

**Issue by saraedum** [flatsurf/vue-flatsurf#58]
Currently, this triangulation cannot be displayed:
```yaml
vertices:
- - 1
  - -3
  - 2
  - -1
  - 3
  - -2
- - 4
  - -5
  - 6
  - -4
  - 5
  - -6
vectors:
  1:
    x: 1.0
    y: 1.0
  2:
    x: -1.0
    y: 0.0
  3:
    x: 0.0
    y: -1.0
  4:
    x: 1.0
    y: 1.0
  5:
    x: 0.0
    y: -1.0
  6:
    x: -1.0
    y: 0.0
```
